import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { formatRunTime, formatRunType, runStateLabels, runStateStyles, tokenSummary } from "@/lib/run-display";
import type { RunDetailResult } from "@/lib/run-history";

export function RunDetail({ result }: { result: RunDetailResult }) {
  if (result.state !== "ready") return <Unavailable state={result.state} />;
  const run = result.run;
  return <div className="grid gap-6" data-run-detail-state="ready" data-run-id={run.id}>
    <Link className="w-fit text-sm font-bold text-accent underline decoration-accent/30 underline-offset-4" href="/runs">← Back to run history</Link>
    <Card className="overflow-hidden border-foreground/25 bg-primary py-0 text-primary-foreground"><CardContent className="grid gap-8 p-[clamp(1.5rem,5vw,4rem)] lg:grid-cols-[minmax(0,1fr)_20rem] lg:items-end"><div><div className="flex flex-wrap gap-3"><Badge className={runStateStyles[run.displayState]} variant="outline">{runStateLabels[run.displayState]}</Badge><Badge className="border-primary-foreground/25 text-primary-foreground" variant="outline">{formatRunType(run.runType)}</Badge></div><p className="mt-10 font-mono text-[0.64rem] font-bold tracking-[0.1em] text-primary-foreground/55 uppercase">Product-level run</p><h2 className="mt-4 max-w-[18ch] font-heading text-[clamp(2.5rem,6vw,5.5rem)] leading-[0.9] font-medium tracking-[-0.06em]">{run.signal?.summary ?? formatRunType(run.runType)}</h2></div><dl className="grid gap-4 border-t border-primary-foreground/20 pt-5 text-sm lg:border-t-0 lg:border-l lg:pt-0 lg:pl-6"><HeroFact label="Trigger" value={run.trigger} /><HeroFact label="Model" value={run.model ?? "Not reported"} /><HeroFact label="Started" value={formatRunTime(run.startedAt)} /><HeroFact label="Completed" value={formatRunTime(run.completedAt)} /></dl></CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_23rem]">
      <div className="grid gap-6">
        {(run.waitingSummary || run.failureSummary) ? <Card className="border-foreground/20 bg-card py-0"><CardContent className="p-[clamp(1.25rem,3vw,2.25rem)]"><SectionLabel>{run.failureSummary ? "Failure state" : "Waiting state"}</SectionLabel><p className="mt-4 text-lg leading-7">{run.failureSummary ?? run.waitingSummary}</p></CardContent></Card> : null}
        <section className="grid gap-4" aria-labelledby="run-steps-title"><div><SectionLabel>Safe product projection</SectionLabel><h2 className="mt-2 font-heading text-[clamp(2rem,4vw,3.4rem)] leading-none tracking-[-0.05em]" id="run-steps-title">Run steps</h2></div><ol className="grid gap-px overflow-hidden rounded-xl border border-foreground/20 bg-foreground/15">{run.steps.map((step, index) => <li className="grid gap-4 bg-card p-[clamp(1.25rem,3vw,2rem)] md:grid-cols-[3rem_minmax(0,1fr)_auto]" data-run-step key={step.id}><span className="font-mono text-xs font-bold text-accent">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-heading text-xl">{step.label}</h3><p className="mt-1 font-mono text-[0.62rem] font-bold tracking-[0.06em] text-accent uppercase">{step.status} · {step.model ?? "model unavailable"}</p><p className="mt-3 text-sm text-muted-foreground">{tokenSummary(step)}</p>{step.failureSummary ? <p className="mt-3 text-sm text-destructive">{step.failureSummary}</p> : null}</div><time className="text-xs text-muted-foreground" dateTime={step.startedAt}>{formatRunTime(step.startedAt)}</time></li>)}</ol></section>
        <section className="grid gap-4" aria-labelledby="run-traces-title"><div><SectionLabel>Linked, never copied</SectionLabel><h2 className="mt-2 font-heading text-[clamp(2rem,4vw,3.4rem)] leading-none tracking-[-0.05em]" id="run-traces-title">Execution traces</h2></div><div className="grid gap-3">{run.traces.map((trace) => <Card className="border-foreground/20 bg-card py-0" data-trace-availability={trace.availability} key={trace.id}><CardContent className="flex flex-col justify-between gap-4 p-[clamp(1.25rem,3vw,2rem)] sm:flex-row sm:items-center"><div><p className="font-mono text-[0.62rem] font-bold tracking-[0.08em] text-muted-foreground uppercase">{trace.kind}</p><h3 className="mt-2 font-heading text-2xl tracking-[-0.035em]">{trace.label}</h3>{trace.unavailableReason ? <p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{trace.unavailableReason}</p> : null}</div>{trace.availability === "available" && trace.url ? <a className="shrink-0 text-sm font-bold text-accent underline underline-offset-4" href={trace.url} rel="noreferrer" target="_blank">Open trace ↗</a> : <Badge variant="outline">Unavailable</Badge>}</CardContent></Card>)}</div></section>
      </div>
      <aside className="h-fit rounded-xl border border-foreground/20 bg-card p-[clamp(1.25rem,3vw,2rem)] xl:sticky xl:top-6"><SectionLabel>Run references</SectionLabel><h2 className="mt-3 font-heading text-3xl leading-none tracking-[-0.04em]">Follow the durable source.</h2><dl className="mt-6 grid gap-5 border-t border-foreground/15 pt-6 text-sm"><SideFact label="Eve session" value={run.sessionId} /><SideFact label="Eve run" value={run.runId} /><SideFact label="Workflow object" value={run.workflowId ?? "Not linked"} /><SideFact label="Related signal" value={run.signal?.id ?? "Not linked"} /><SideFact label="Usage" value={tokenSummary(run)} /><SideFact label="Expires" value={`${formatRunTime(run.expiresAt)} · ${run.retentionDays}-day index retention`} /></dl><p className="mt-6 border-t border-foreground/15 pt-6 text-xs leading-5 text-muted-foreground">Expiry deletes this index row and its step projections. Eve, Vercel, and OpenTelemetry retain their own traces under their own policies.</p></aside>
    </div>
  </div>;
}

function Unavailable({ state }: { state: Exclude<RunDetailResult["state"], "ready"> }) { const content = state === "missing" ? ["Run not found", "This product run does not exist or its 30-day index retention has elapsed."] : state === "unauthorized" ? ["Run detail is not authorized", "Sign in with an approved operator account before reading execution metadata."] : state === "invalid-record" ? ["Run record is invalid", "The stored row was not rendered because it does not match the current contract."] : ["Run database unavailable", "Restore database access and apply migrations before reviewing this run."]; return <Card className="min-h-72 border-foreground/20 bg-card py-0" data-run-detail-state={state} role={state === "missing" ? "status" : "alert"}><CardContent className="grid min-h-72 content-center gap-5 p-[clamp(1.5rem,4vw,3.5rem)]"><p className="font-mono text-xs font-bold tracking-[0.1em] text-accent uppercase">Run unavailable</p><h2 className="font-heading text-[clamp(2.2rem,5vw,4.5rem)] leading-none tracking-[-0.055em]">{content[0]}</h2><p className="max-w-xl leading-7 text-muted-foreground">{content[1]}</p><Link className="w-fit text-sm font-bold text-accent underline underline-offset-4" href="/runs">Return to run history</Link></CardContent></Card>; }
function SectionLabel({ children }: { children: string }) { return <p className="font-mono text-[0.64rem] font-bold tracking-[0.1em] text-accent uppercase">{children}</p>; }
function HeroFact({ label, value }: { label: string; value: string }) { return <div><dt className="font-mono text-[0.58rem] font-bold tracking-[0.08em] text-primary-foreground/55 uppercase">{label}</dt><dd className="mt-1.5 capitalize text-primary-foreground/85">{value}</dd></div>; }
function SideFact({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="font-mono text-[0.58rem] font-bold tracking-[0.08em] text-muted-foreground uppercase">{label}</dt><dd className="mt-1.5 break-all">{value}</dd></div>; }
